# Generated by Django 4.2.3 on 2023-07-21 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortenedurl',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
